name: Templates validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install curlylint
        run: pip install curlylint

      - name: Run linter
        run: >
          curlylint --rule 'aria_role: true' \
            --rule 'django_forms_rendering: true' \
            --rule 'html_has_lang: true' \
            --rule 'image_alt: true' \
            --rule 'meta_viewport: true' \
            --rule 'no_autofocus: true' \
            --rule 'tabindex_no_positive: true' \
            --exclude '_modal.html|create_status/layout.html|reading_modals/layout.html' \
            bookwyrm/templates
